name: Build
run-name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Check out repository
        uses: actions/checkout@v4
      - run: make prepare
      - run: make build DEVICE=tanmatsu FAT=1
      - run: mv build/tanmatsu/bootloader/*.bin build/tanmatsu/
      - run: mv build/tanmatsu/bootloader/*.elf build/tanmatsu/
      - run: mv build/tanmatsu/partition_table/*.bin build/tanmatsu/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tanmatsu
          path: |
            build/tanmatsu/*.bin
            build/tanmatsu/tanmatsu-launcher.elf
            build/tanmatsu/bootloader.bin
            build/tanmatsu/bootloader.elf
            build/tanmatsu/partition-table.bin
